"""Changes

Revision ID: 4b975b5de635
Revises: b21384c87f88
Create Date: 2025-03-17 19:01:48.942479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b975b5de635'
down_revision: Union[str, None] = 'b21384c87f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'depth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('depth', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
