"""add color to categories table

Revision ID: 67129e01bf8e
Revises: 4b975b5de635
Create Date: 2025-03-29 20:35:28.590034

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67129e01bf8e"
down_revision: Union[str, None] = "4b975b5de635"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("color", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("categories", "color")
    # ### end Alembic commands ###
